name: Execute Swift package command-line tool

on:
  push:
    branches: ['main']
jobs:
  swiftformat:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache/Restore Mint packages
      id: mint-cache
      uses: actions/cache@v2
      with:
          path: ${{ github.workspace }}/mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: ${{ runner.os }}-mint-
    - name: Install package manager "Mint" to install and run Swift command line tool packages
      run: |
          brew upgrade mint || brew install mint || true
    - name: Install command line tool (if not yet cached)
      if: steps.mint-cache.outputs.cache-hit != 'true'
      run: mint bootstrap
    - name: Run command line tool
      run: mint run swiftformat --verbose .

